import type { Aninmal } from '@/types';
export const ANINMALS: Aninmal[] = [
  {
    name: "Formal chikcen",
    realAnimal: "Penguin",
    image: "formal_chikcen.jpg",
    description: "Looking dapper and ready for a formal event.",
  },
  {
    name: "Forest gorgi",
    realAnimal: "Fox",
    image: "forest_corgi.jpg",
    description: "Maybe he just returned from ISS?",
  },
  {
    name: "Danger zebra",
    realAnimal: "Tiger",
    image: "danger_zebra.jpg",
    description: "Has a tank named after him.",
  },
  {
    name: "Rude Honker",
    realAnimal: "Goose",
    image: "rude_honker.jpg",
    description: "So rude, such honker.",
  },
  {
    name: "Grandiose gull",
    realAnimal: "Alpatross",
    image: "grandiose_gull.jpg",
    description: "Majestic and wingspan of a plane.",
  },
  {
    name: "Mobile home lizard",
    realAnimal: "Tortoise",
    image: "mobile_home_lizard.jpg",
    description: "A tech tortoise!",
  },
  {
    name: "Treefloof",
    realAnimal: "Koala",
    image: "",
    description: "",
  },
  {
    name: "Disco turkey",
    realAnimal: "Peacock",
    image: "",
    description: "",
  },
  {
    name: "Danger noodle",
    realAnimal: "Rattlesnake",
    image: "",
    description: "",
  },
  {
    name: "Sea flap flap",
    realAnimal: "Stingray",
    image: "",
    description: "",
  },
  {
    name: "Murder log",
    realAnimal: "Alligator",
    image: "",
    description: "",
  },
  {
    name: "Wizard cow",
    realAnimal: "Mountain Goat",
    image: "",
    description: "",
  },
  {
    name: "Stab rabbit",
    realAnimal: "Porcupine",
    image: "",
    description: "",
  },
  {
    name: "Fart squirrel",
    realAnimal: "Skunk",
    image: "",
    description: "",
  },
  {
    name: "Blub blub doggo",
    realAnimal: "Seal",
    image: "",
    description: "",
  },
  {
    name: "Trouble bubble",
    realAnimal: "Jellyfish",
    image: "",
    description: "",
  },
  {
    name: "Aquatic sock puppet",
    realAnimal: "Muray eel",
    image: "",
    description: "",
  },
  {
    name: "Water pistachio",
    realAnimal: "Seashell",
    image: "",
    description: "",
  },
  {
    name: "Cheese boi",
    realAnimal: "Field mouse",
    image: "",
    description: "",
  },
  {
    name: "Noodle bear",
    realAnimal: "Ant eater",
    image: "",
    description: "",
  },
  {
    name: "Booblesnoot" ,
    realAnimal: "Rabbit",
    image: "",
    description: "",
  },
  {
    name: "Murder torpedo",
    realAnimal: "Shark",
    image: "",
    description: "",
  },
  {
    name: "Hop pocket",
    realAnimal: "Kangaroo",
    image: "",
    description: "",
  },
  {
    name: "Trash panda",
    realAnimal: "Raccoon",
    image: "",
    description: "",
  },
  {
    name: "Patience monkey",
    realAnimal: "Sloth",
    image: "",
    description: "",
  },
  {
    name: "Death cuddle",
    realAnimal: "Bear",
    image: "",
    description: "",
  },
  {
    name: "Prison Pony",
    realAnimal: "Zebra",
    image: "",
    description: "",
  },
  {
    name: "Sand Moose",
    realAnimal: "Camel",
    image: "",
    description: "",
  },
  {
    name: "Dirt Noodol",
    realAnimal: "Worm",
    image: "",
    description: "",
  },
  {
    name: "Cave Pupper",
    realAnimal: "Bat",
    image: "",
    description: "",
  },
  {
    name: "Lumber Squirrel",
    realAnimal: "Beaver",
    image: "",
    description: "",
  },
  {
    name: "Water Weasel",
    realAnimal: "Otter",
    image: "",
    description: "",
  },
]